name: appXXXX
stack: apps/custom
image: jwilder/whoami:latest
host: node2

volumes:
  data: '/var/www/html'
  logs: '/var/logs'
  # custom: # warning: custom volume mounts need to exist on the host (won't be created by dockerpilot)
  #   - '{appDir}/custom:/var/custom'

# environment:
  # TEST: test-value

database:
  host: db
  user: appXXXX
  password: secret
  name: appXXXX

network:
  port: 80
  domains: appXXXX.getsitepilot.com

limits:
  cpu: 1
  memory: 512M