remote_theme: "mmistakes/minimal-mistakes"
repository: sitepilot/dockerpilot
url: http://localhost:4000

include: ["_pages"]

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-remote-theme
- jemoji