- hosts: all
  tasks:
  - name: Check if portainer data dir exists.
    stat:
      path: "{{ portainerStoragePath }}"
    register: portainerDetails

  - name: Check if mysql data dir exists.
    stat:
      path: "{{ mysqlStoragePath }}"
    register: mysqlDetails

  - name: Check if config data dir exists.
    stat:
      path: "{{ configStoragePath }}"
    register: configDetails

  - name: Backup Portainer data dir.
    shell: source /home/{{ serverUser }}/.restic-env && restic backup --tag portainer {{ portainerStoragePath }}
    args:
      executable: /bin/bash
    when: portainerDetails.stat.exists

  - name: Backup MySQL data dir.
    shell: source /home/{{ serverUser }}/.restic-env && restic backup --tag mysql {{ mysqlStoragePath }}
    args:
      executable: /bin/bash
    when: mysqlDetails.stat.exists

  - name: Backup config data dir.
    shell: source /home/{{ serverUser }}/.restic-env && restic backup --tag config {{ configStoragePath }}
    args:
      executable: /bin/bash
    when: configDetails.stat.exists