- hosts: '{{ host }}'
  tasks:
  - name: Check if application data dir exists.
    stat:
      path: "{{ appDataDir }}"
    register: appDetails

  - name: Backup application database of {{ app }}.
    shell: CONTAINER=$(docker ps -f "name={{ app }}" -q) && if [ ! -z $CONTAINER ]; then docker exec $CONTAINER dp-backup; fi
    args:
      executable: /bin/bash
    when: appDetails.stat.exists

  - name: Backup application data dir of {{ app }}.
    become: yes
    become_user: "{{ becomeUser }}"
    become_method: su
    shell: source /home/{{ becomeUser }}/.restic-env && restic backup --tag {{ app }} {{ appDataDir }} {{appBackupDir}}
    args:
      executable: /bin/bash
    when: appDetails.stat.exists